create table note_source (
    id bigint generated by default as identity primary key,
    scope varchar(32) not null,
    owner_user_id bigint,
    title varchar(255) not null,
    content text not null,
    tags jsonb not null default '[]'::jsonb,
    created_at timestamptz not null default now(),
    updated_at timestamptz not null default now(),
    constraint fk_note_source_owner_user
        foreign key (owner_user_id) references user_account(id) on delete set null,
    constraint ck_note_source_scope
        check (
            (scope = 'SYSTEM' and owner_user_id is null)
            or (scope = 'USER' and owner_user_id is not null)
        ),
    constraint ck_note_source_tags_is_array
        check (jsonb_typeof(tags) = 'array')
);

create unique index uk_note_source_user_title on note_source(owner_user_id, title) where scope = 'USER';
create unique index uk_note_source_system_title on note_source(title) where scope = 'SYSTEM';
create index idx_note_source_scope_owner on note_source(scope, owner_user_id);

alter table note rename to note_legacy;

drop index if exists idx_note_due_at;
drop index if exists idx_note_mastery_status;
drop index if exists idx_note_updated_at;
drop index if exists idx_note_weak_flag;

create table note (
    id bigint generated by default as identity primary key,
    note_source_id bigint not null,
    user_id bigint not null,
    review_count integer not null default 0,
    mastery_status varchar(32) not null default 'UNSTARTED',
    due_at timestamptz not null,
    last_reviewed_at timestamptz,
    fsrs_card_json text not null,
    weak_flag boolean not null default false,
    weak_marked_at timestamptz,
    last_review_rating varchar(16),
    created_at timestamptz not null default now(),
    updated_at timestamptz not null default now(),
    constraint fk_note_source
        foreign key (note_source_id) references note_source(id) on delete cascade,
    constraint fk_note_user
        foreign key (user_id) references user_account(id) on delete cascade,
    constraint uk_note_user_source
        unique (user_id, note_source_id),
    constraint ck_note_review_count_non_negative
        check (review_count >= 0),
    constraint ck_note_mastery_status
        check (mastery_status in ('UNSTARTED', 'LEARNING', 'CONSOLIDATING', 'MASTERED')),
    constraint ck_note_last_review_rating
        check (last_review_rating is null or last_review_rating in ('AGAIN', 'HARD', 'GOOD', 'EASY'))
);

create index idx_note_user_due_at on note(user_id, due_at);
create index idx_note_user_mastery_status on note(user_id, mastery_status);
create index idx_note_user_updated_at on note(user_id, updated_at desc, id desc);
create index idx_note_user_weak_flag on note(user_id, weak_flag, weak_marked_at desc, id desc);
create index idx_note_source_id on note(note_source_id);

insert into note_source (
    id,
    scope,
    owner_user_id,
    title,
    content,
    tags,
    created_at,
    updated_at
)
select
    id,
    'USER',
    1,
    title,
    content,
    tags,
    created_at,
    updated_at
from note_legacy;

insert into note (
    id,
    note_source_id,
    user_id,
    review_count,
    mastery_status,
    due_at,
    last_reviewed_at,
    fsrs_card_json,
    weak_flag,
    weak_marked_at,
    last_review_rating,
    created_at,
    updated_at
)
select
    id,
    id,
    1,
    review_count,
    mastery_status,
    due_at,
    last_reviewed_at,
    fsrs_card_json,
    weak_flag,
    weak_marked_at,
    last_review_rating,
    created_at,
    updated_at
from note_legacy;

select setval(
    pg_get_serial_sequence('note_source', 'id'),
    (select max(id) from note_source)
);

select setval(
    pg_get_serial_sequence('note', 'id'),
    (select max(id) from note)
);

alter table note_review_log
    drop constraint fk_note_review_log_note;

alter table note_review_log
    add constraint fk_note_review_log_note
        foreign key (note_id) references note(id) on delete cascade;

drop table note_legacy;
